# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: usuario.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\rusuario.proto\x12\x07usuario"E\n\x07Usuario\x12\n\n\x02ID\x18\x01 \x01(\x05\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\r\n\x05idade\x18\x03 \x01(\x05\x12\x11\n\tplaylists\x18\x04 \x03(\x05"\x17\n\tUsuarioID\x12\n\n\x02ID\x18\x01 \x01(\x05"\x1b\n\x08Resposta\x12\x0f\n\x07message\x18\x01 \x01(\t"\x07\n\x05\x45mpty"1\n\x0bUsuarioList\x12"\n\x08usuarios\x18\x01 \x03(\x0b\x32\x10.usuario.Usuario2\xa0\x02\n\x0eUsuarioService\x12\x33\n\x0c\x43riarUsuario\x12\x10.usuario.Usuario\x1a\x11.usuario.Resposta\x12\x32\n\nLerUsuario\x12\x12.usuario.UsuarioID\x1a\x10.usuario.Usuario\x12\x37\n\x10\x41tualizarUsuario\x12\x10.usuario.Usuario\x1a\x11.usuario.Resposta\x12\x37\n\x0e\x44\x65letarUsuario\x12\x12.usuario.UsuarioID\x1a\x11.usuario.Resposta\x12\x33\n\x0bLerUsuarios\x12\x0e.usuario.Empty\x1a\x14.usuario.UsuarioListb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "usuario_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_USUARIO"]._serialized_start = 26
    _globals["_USUARIO"]._serialized_end = 95
    _globals["_USUARIOID"]._serialized_start = 97
    _globals["_USUARIOID"]._serialized_end = 120
    _globals["_RESPOSTA"]._serialized_start = 122
    _globals["_RESPOSTA"]._serialized_end = 149
    _globals["_EMPTY"]._serialized_start = 151
    _globals["_EMPTY"]._serialized_end = 158
    _globals["_USUARIOLIST"]._serialized_start = 160
    _globals["_USUARIOLIST"]._serialized_end = 209
    _globals["_USUARIOSERVICE"]._serialized_start = 212
    _globals["_USUARIOSERVICE"]._serialized_end = 500
# @@protoc_insertion_point(module_scope)
