# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: usuario.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rusuario.proto\x12\nmusica_app\"E\n\x07Usuario\x12\n\n\x02ID\x18\x01 \x01(\x05\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\r\n\x05idade\x18\x03 \x01(\x05\x12\x11\n\tplaylists\x18\x04 \x03(\x05\"3\n\x06Musica\x12\n\n\x02ID\x18\x01 \x01(\x05\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\x0f\n\x07\x61rtista\x18\x03 \x01(\t\"\x17\n\tUsuarioID\x12\n\n\x02ID\x18\x01 \x01(\x05\"\x16\n\x08MusicaID\x12\n\n\x02ID\x18\x01 \x01(\x05\"\x1b\n\x08Resposta\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\"4\n\x0bUsuarioList\x12%\n\x08usuarios\x18\x01 \x03(\x0b\x32\x13.musica_app.Usuario\"1\n\nMusicaList\x12#\n\x07musicas\x18\x01 \x03(\x0b\x32\x12.musica_app.Musica2\xbe\x02\n\x0eUsuarioService\x12\x39\n\x0c\x43riarUsuario\x12\x13.musica_app.Usuario\x1a\x14.musica_app.Resposta\x12\x38\n\nLerUsuario\x12\x15.musica_app.UsuarioID\x1a\x13.musica_app.Usuario\x12=\n\x10\x41tualizarUsuario\x12\x13.musica_app.Usuario\x1a\x14.musica_app.Resposta\x12=\n\x0e\x44\x65letarUsuario\x12\x15.musica_app.UsuarioID\x1a\x14.musica_app.Resposta\x12\x39\n\x0bLerUsuarios\x12\x11.musica_app.Empty\x1a\x17.musica_app.UsuarioList2\xb2\x02\n\rMusicaService\x12\x37\n\x0b\x43riarMusica\x12\x12.musica_app.Musica\x1a\x14.musica_app.Resposta\x12\x35\n\tLerMusica\x12\x14.musica_app.MusicaID\x1a\x12.musica_app.Musica\x12;\n\x0f\x41tualizarMusica\x12\x12.musica_app.Musica\x1a\x14.musica_app.Resposta\x12;\n\rDeletarMusica\x12\x14.musica_app.MusicaID\x1a\x14.musica_app.Resposta\x12\x37\n\nLerMusicas\x12\x11.musica_app.Empty\x1a\x16.musica_app.MusicaListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'usuario_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USUARIO']._serialized_start=29
  _globals['_USUARIO']._serialized_end=98
  _globals['_MUSICA']._serialized_start=100
  _globals['_MUSICA']._serialized_end=151
  _globals['_USUARIOID']._serialized_start=153
  _globals['_USUARIOID']._serialized_end=176
  _globals['_MUSICAID']._serialized_start=178
  _globals['_MUSICAID']._serialized_end=200
  _globals['_RESPOSTA']._serialized_start=202
  _globals['_RESPOSTA']._serialized_end=229
  _globals['_EMPTY']._serialized_start=231
  _globals['_EMPTY']._serialized_end=238
  _globals['_USUARIOLIST']._serialized_start=240
  _globals['_USUARIOLIST']._serialized_end=292
  _globals['_MUSICALIST']._serialized_start=294
  _globals['_MUSICALIST']._serialized_end=343
  _globals['_USUARIOSERVICE']._serialized_start=346
  _globals['_USUARIOSERVICE']._serialized_end=664
  _globals['_MUSICASERVICE']._serialized_start=667
  _globals['_MUSICASERVICE']._serialized_end=973
# @@protoc_insertion_point(module_scope)
